name: braze_plugin
description: This is the Braze plugin for Flutter. Effective marketing automation is an essential part of successfully scaling and managing your business.
version: 1.0.0
homepage: https://www.braze.com/

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.braze.brazeplugin
    pluginClass: BrazePlugin
